pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Compile $(buildConfiguration) Build'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--logger:trx --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet Package'
  inputs:
    command: pack
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'Brigadier.NET/Brigadier.NET.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts to VSTS'