name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)

variables:
  buildConfiguration: 'Release'
  majorVersion: 2
  minorVersion: 0

jobs:
- template: azure-pipelines-build.yml
  parameters: 
    majorVersion: $(majorVersion)
    minorVersion: $(minorVersion)
